apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-config
data:
  config.yaml: |
    service:
      extensions: [jaeger_storage, jaeger_query]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger_storage_exporter, spanmetrics]
        metrics/spanmetrics:
          receivers: [spanmetrics]
          exporters: [prometheus]
        metrics:
          receivers: [otlp]
          exporters: [prometheus]
      telemetry:
        logs:
          level: info
        metrics:
          level: none  # Deshabilitar métricas de telemetry

    extensions:
      jaeger_query:
        storage:
          traces: trace_storage
          metrics: metrics_storage
      jaeger_storage:
        backends:
          trace_storage:
            memory:
              max_traces: 10000
        metric_backends:
          metrics_storage:
            prometheus:
              endpoint: http://prometheus
              normalize_calls: true
              normalize_duration: true

    connectors:
      spanmetrics:

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"

    processors:
      batch:

    exporters:
      jaeger_storage_exporter:
        trace_storage: trace_storage
      prometheus:
        endpoint: "0.0.0.0:8888"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: cr.jaegertracing.io/jaegertracing/jaeger:latest
        args: ["--config=/etc/jaeger/config.yaml"]
        ports:
        - containerPort: 16686
          name: ui
        - containerPort: 4317
          name: grpc
        - containerPort: 4318
          name: http
        - containerPort: 8888
          name: metrics
        env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        - name: OTEL_TRACES_SAMPLER
          value: "always_off"
        volumeMounts:
        - name: config
          mountPath: /etc/jaeger
      volumes:
      - name: config
        configMap:
          name: jaeger-config
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
  - port: 80
    targetPort: 16686
    name: ui
  - port: 4317
    targetPort: 4317
    name: grpc
  - port: 4318
    targetPort: 4318
    name: http
  - port: 8888
    targetPort: 8888
    name: metrics
