kind: pipeline
type: kubernetes
name: ocr-system

service_account_name: drone-deployer

trigger:
  branch:
    - main
    - k8s-deploy
  event:
    - push

steps:
  - name: Build OCR System
    image: plugins/docker
    depends_on: [clone]
    settings:
      context: backend
      dockerfile: backend/Dockerfile
      registry:
        from_secret: docker_registry
      repo:
        from_secret: docker_repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      insecure:
        from_secret: docker_insecure
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest

  - name: Build OCR System Image
    image: plugins/docker
    depends_on: [clone]
    settings:
      context: backend
      dockerfile: backend/Dockerfile.ocr
      registry:
        from_secret: docker_registry
      repo:
        from_secret: docker_repo_image
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest

  - name: Setup Infrastructure Configuration
    image: alpine/k8s:1.32.11
    depends_on: [clone]
    commands:
      - |
        if [ "${DRONE_BRANCH}" = "main" ]; then
          NS="ocr-system"
        else
          NS="ocr-system-staging"
        fi

        echo "Using namespace: ${NS}"
        kubectl apply -n "${NS}" -f k8s/postgres.yaml
