apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seaweedfs-volume
spec:
  serviceName: "seaweedfs-volume"
  replicas: 1
  selector:
    matchLabels:
      app: seaweedfs-volume
  template:
    metadata:
      labels:
        app: seaweedfs-volume
    spec:
      containers:
        - name: volume
          image: chrislusf/seaweedfs:4.00
          ports:
            - containerPort: 8080
            - containerPort: 18080
            - containerPort: 9325
          args:
            [
              "volume",
              "-mserver=seaweedfs-master:9333",
              "-ip.bind=0.0.0.0",
              "-port=8080",
              "-metricsPort=9325",
            ]
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-volume
spec:
  selector:
    app: seaweedfs-volume
  ports:
    - port: 8080
      targetPort: 8080
