// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { FilePagesServiceGetFilePagesData, FilePagesServiceGetFilePagesErrors, FilePagesServiceGetFilePagesResponses, FilesServiceDeleteFilesData, FilesServiceDeleteFilesErrors, FilesServiceDeleteFilesResponses, FilesServiceGetFilesData, FilesServiceGetFilesErrors, FilesServiceGetFilesResponses, HealthServiceHealthData, HealthServiceHealthErrors, HealthServiceHealthResponses, StorageServiceConfirmFileUploadData, StorageServiceConfirmFileUploadErrors, StorageServiceConfirmFileUploadResponses, StorageServiceGetFileUrlData, StorageServiceGetFileUrlErrors, StorageServiceGetFileUrlResponses, StorageServiceGetUploadUrlData, StorageServiceGetUploadUrlErrors, StorageServiceGetUploadUrlResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health check
 *
 * Returns the health status of the service.
 */
export const healthServiceHealth = <ThrowOnError extends boolean = false>(options?: Options<HealthServiceHealthData, ThrowOnError>) => (options?.client ?? client).get<HealthServiceHealthResponses, HealthServiceHealthErrors, ThrowOnError>({ url: '/healthz', ...options });

/**
 * Confirm File Upload
 *
 * Confirms that a file has been uploaded.
 */
export const storageServiceConfirmFileUpload = <ThrowOnError extends boolean = false>(options: Options<StorageServiceConfirmFileUploadData, ThrowOnError>) => (options.client ?? client).post<StorageServiceConfirmFileUploadResponses, StorageServiceConfirmFileUploadErrors, ThrowOnError>({
    url: '/storage/confirm-upload',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get File URL
 *
 * Retrieves a pre-signed URL for downloading a file.
 */
export const storageServiceGetFileUrl = <ThrowOnError extends boolean = false>(options: Options<StorageServiceGetFileUrlData, ThrowOnError>) => (options.client ?? client).get<StorageServiceGetFileUrlResponses, StorageServiceGetFileUrlErrors, ThrowOnError>({ url: '/storage/file-url/{fileKey}', ...options });

/**
 * Delete Files
 *
 * Deletes multiple files by their keys.
 */
export const filesServiceDeleteFiles = <ThrowOnError extends boolean = false>(options?: Options<FilesServiceDeleteFilesData, ThrowOnError>) => (options?.client ?? client).delete<FilesServiceDeleteFilesResponses, FilesServiceDeleteFilesErrors, ThrowOnError>({ url: '/storage/files', ...options });

/**
 * Get Files
 *
 * Retrieves a paginated list of files.
 */
export const filesServiceGetFiles = <ThrowOnError extends boolean = false>(options?: Options<FilesServiceGetFilesData, ThrowOnError>) => (options?.client ?? client).get<FilesServiceGetFilesResponses, FilesServiceGetFilesErrors, ThrowOnError>({ url: '/storage/files', ...options });

/**
 * Get File Pages
 *
 * Retrieve pages of a file by file key
 */
export const filePagesServiceGetFilePages = <ThrowOnError extends boolean = false>(options: Options<FilePagesServiceGetFilePagesData, ThrowOnError>) => (options.client ?? client).get<FilePagesServiceGetFilePagesResponses, FilePagesServiceGetFilePagesErrors, ThrowOnError>({ url: '/storage/files/{fileKey}/pages', ...options });

/**
 * Get Upload URL
 *
 * Generates a pre-signed URL for uploading files.
 */
export const storageServiceGetUploadUrl = <ThrowOnError extends boolean = false>(options?: Options<StorageServiceGetUploadUrlData, ThrowOnError>) => (options?.client ?? client).get<StorageServiceGetUploadUrlResponses, StorageServiceGetUploadUrlErrors, ThrowOnError>({ url: '/storage/upload-url', ...options });
