// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { HealthServiceHealthData, HealthServiceHealthErrors, HealthServiceHealthResponses, StorageServiceConfirmFileUploadData, StorageServiceConfirmFileUploadErrors, StorageServiceConfirmFileUploadResponses, StorageServiceGetUploadUrlData, StorageServiceGetUploadUrlErrors, StorageServiceGetUploadUrlResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health check
 *
 * Returns the health status of the service.
 */
export const healthServiceHealth = <ThrowOnError extends boolean = false>(options?: Options<HealthServiceHealthData, ThrowOnError>) => (options?.client ?? client).get<HealthServiceHealthResponses, HealthServiceHealthErrors, ThrowOnError>({ url: '/health', ...options });

/**
 * Confirm File Upload
 *
 * Confirms that a file has been uploaded.
 */
export const storageServiceConfirmFileUpload = <ThrowOnError extends boolean = false>(options: Options<StorageServiceConfirmFileUploadData, ThrowOnError>) => (options.client ?? client).post<StorageServiceConfirmFileUploadResponses, StorageServiceConfirmFileUploadErrors, ThrowOnError>({
    url: '/storage/confirm-upload',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Upload URL
 *
 * Generates a pre-signed URL for uploading files.
 */
export const storageServiceGetUploadUrl = <ThrowOnError extends boolean = false>(options?: Options<StorageServiceGetUploadUrlData, ThrowOnError>) => (options?.client ?? client).get<StorageServiceGetUploadUrlResponses, StorageServiceGetUploadUrlErrors, ThrowOnError>({ url: '/storage/upload-url', ...options });
