// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type CorePagination = {
    pageNumber?: number;
    pageSize?: number;
    totalItems?: number;
    hasNextPage?: boolean;
};

export type HealthHealthResponse = {
    status?: string;
};

export type OcrFilePage = {
    pageNumber?: number;
    imageUrl?: string;
};

export type OcrGetFilePagesResponse = {
    pagination?: CorePagination;
    pages?: Array<OcrFilePage>;
};

export type ProtobufAny = {
    '@type'?: string;
    [key: string]: unknown | string | undefined;
};

export type RpcStatus = {
    code?: number;
    message?: string;
    details?: Array<ProtobufAny>;
};

export type StorageConfirmFileUploadRequest = {
    fileName?: string;
    fileKey?: string;
};

export type StorageFile = {
    fileName?: string;
    fileKey?: string;
    fileSize?: string;
    fileType?: string;
    createdAt?: string;
};

export type StorageGetFileUrlResponse = {
    fileUrl?: string;
};

export type StorageGetFilesResponse = {
    pagination?: CorePagination;
    files?: Array<StorageFile>;
};

export type StorageGetUploadUrlResponse = {
    uploadUrl?: string;
    fileKey?: string;
};

export type HealthServiceHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthServiceHealthErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type HealthServiceHealthError = HealthServiceHealthErrors[keyof HealthServiceHealthErrors];

export type HealthServiceHealthResponses = {
    /**
     * A successful response.
     */
    200: HealthHealthResponse;
};

export type HealthServiceHealthResponse = HealthServiceHealthResponses[keyof HealthServiceHealthResponses];

export type StorageServiceConfirmFileUploadData = {
    body: StorageConfirmFileUploadRequest;
    path?: never;
    query?: never;
    url: '/storage/confirm-upload';
};

export type StorageServiceConfirmFileUploadErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type StorageServiceConfirmFileUploadError = StorageServiceConfirmFileUploadErrors[keyof StorageServiceConfirmFileUploadErrors];

export type StorageServiceConfirmFileUploadResponses = {
    /**
     * A successful response.
     */
    200: {
        [key: string]: unknown;
    };
};

export type StorageServiceConfirmFileUploadResponse = StorageServiceConfirmFileUploadResponses[keyof StorageServiceConfirmFileUploadResponses];

export type StorageServiceGetFileUrlData = {
    body?: never;
    path: {
        fileKey: string;
    };
    query?: never;
    url: '/storage/file-url/{fileKey}';
};

export type StorageServiceGetFileUrlErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type StorageServiceGetFileUrlError = StorageServiceGetFileUrlErrors[keyof StorageServiceGetFileUrlErrors];

export type StorageServiceGetFileUrlResponses = {
    /**
     * A successful response.
     */
    200: StorageGetFileUrlResponse;
};

export type StorageServiceGetFileUrlResponse = StorageServiceGetFileUrlResponses[keyof StorageServiceGetFileUrlResponses];

export type FilesServiceDeleteFilesData = {
    body?: never;
    path?: never;
    query?: {
        fileKeys?: Array<string>;
    };
    url: '/storage/files';
};

export type FilesServiceDeleteFilesErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type FilesServiceDeleteFilesError = FilesServiceDeleteFilesErrors[keyof FilesServiceDeleteFilesErrors];

export type FilesServiceDeleteFilesResponses = {
    /**
     * A successful response.
     */
    200: {
        [key: string]: unknown;
    };
};

export type FilesServiceDeleteFilesResponse = FilesServiceDeleteFilesResponses[keyof FilesServiceDeleteFilesResponses];

export type FilesServiceGetFilesData = {
    body?: never;
    path?: never;
    query?: {
        pageNumber?: number;
        pageSize?: number;
    };
    url: '/storage/files';
};

export type FilesServiceGetFilesErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type FilesServiceGetFilesError = FilesServiceGetFilesErrors[keyof FilesServiceGetFilesErrors];

export type FilesServiceGetFilesResponses = {
    /**
     * A successful response.
     */
    200: StorageGetFilesResponse;
};

export type FilesServiceGetFilesResponse = FilesServiceGetFilesResponses[keyof FilesServiceGetFilesResponses];

export type FilePagesServiceGetFilePagesData = {
    body?: never;
    path: {
        fileKey: string;
    };
    query?: {
        pageNumber?: number;
        pageSize?: number;
    };
    url: '/storage/files/{fileKey}/pages';
};

export type FilePagesServiceGetFilePagesErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type FilePagesServiceGetFilePagesError = FilePagesServiceGetFilePagesErrors[keyof FilePagesServiceGetFilePagesErrors];

export type FilePagesServiceGetFilePagesResponses = {
    /**
     * A successful response.
     */
    200: OcrGetFilePagesResponse;
};

export type FilePagesServiceGetFilePagesResponse = FilePagesServiceGetFilePagesResponses[keyof FilePagesServiceGetFilePagesResponses];

export type StorageServiceGetUploadUrlData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/storage/upload-url';
};

export type StorageServiceGetUploadUrlErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type StorageServiceGetUploadUrlError = StorageServiceGetUploadUrlErrors[keyof StorageServiceGetUploadUrlErrors];

export type StorageServiceGetUploadUrlResponses = {
    /**
     * A successful response.
     */
    200: StorageGetUploadUrlResponse;
};

export type StorageServiceGetUploadUrlResponse = StorageServiceGetUploadUrlResponses[keyof StorageServiceGetUploadUrlResponses];
