FROM golang:alpine AS build
RUN apk add --no-cache git
RUN go install github.com/go-delve/delve/cmd/dlv@latest

FROM alpine:latest

WORKDIR /app
ARG BINARY=app
COPY ${BINARY} .
COPY --from=build /go/bin/dlv /dlv