// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file_pages.sql

package ocrdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFilePage = `-- name: CreateFilePage :exec
INSERT INTO ocr.file_pages (id, file_id, page_image_key, page_number)
VALUES ($1, $2, $3, $4)
`

type CreateFilePageParams struct {
	ID           pgtype.UUID `json:"id"`
	FileID       pgtype.UUID `json:"file_id"`
	PageImageKey string      `json:"page_image_key"`
	PageNumber   int32       `json:"page_number"`
}

func (q *Queries) CreateFilePage(ctx context.Context, arg CreateFilePageParams) error {
	_, err := q.db.Exec(ctx, createFilePage,
		arg.ID,
		arg.FileID,
		arg.PageImageKey,
		arg.PageNumber,
	)
	return err
}

const deleteFilePagesByFileID = `-- name: DeleteFilePagesByFileID :exec
DELETE FROM ocr.file_pages
WHERE file_id = $1
`

func (q *Queries) DeleteFilePagesByFileID(ctx context.Context, fileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFilePagesByFileID, fileID)
	return err
}

const getFilePagesByFileID = `-- name: GetFilePagesByFileID :many
SELECT id, file_id, page_image_key, page_number, text_content, error_message, created_at, updated_at
FROM ocr.file_pages
WHERE file_id = $1
ORDER BY page_number ASC
`

func (q *Queries) GetFilePagesByFileID(ctx context.Context, fileID pgtype.UUID) ([]OcrFilePage, error) {
	rows, err := q.db.Query(ctx, getFilePagesByFileID, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OcrFilePage
	for rows.Next() {
		var i OcrFilePage
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.PageImageKey,
			&i.PageNumber,
			&i.TextContent,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFilePageText = `-- name: UpdateFilePageText :one
UPDATE ocr.file_pages
SET text_content = $2
WHERE id = $1
RETURNING id, file_id, page_image_key, page_number, text_content, error_message, created_at, updated_at
`

type UpdateFilePageTextParams struct {
	ID          pgtype.UUID `json:"id"`
	TextContent *string     `json:"text_content"`
}

func (q *Queries) UpdateFilePageText(ctx context.Context, arg UpdateFilePageTextParams) (OcrFilePage, error) {
	row := q.db.QueryRow(ctx, updateFilePageText, arg.ID, arg.TextContent)
	var i OcrFilePage
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.PageImageKey,
		&i.PageNumber,
		&i.TextContent,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
