// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package ocrdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OcrFilePage struct {
	ID           pgtype.UUID        `json:"id"`
	FileID       pgtype.UUID        `json:"file_id"`
	PageImageKey string             `json:"page_image_key"`
	PageNumber   int32              `json:"page_number"`
	TextContent  *string            `json:"text_content"`
	ErrorMessage *string            `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type OcrOutbox struct {
	EventID     pgtype.UUID        `json:"event_id"`
	EventType   string             `json:"event_type"`
	Payload     []byte             `json:"payload"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}
