// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package ocrdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO ocr.outbox (event_id, event_type, payload)
VALUES ($1, $2, $3)
`

type CreateOutboxEventParams struct {
	EventID   pgtype.UUID `json:"event_id"`
	EventType string      `json:"event_type"`
	Payload   []byte      `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.Exec(ctx, createOutboxEvent, arg.EventID, arg.EventType, arg.Payload)
	return err
}

const getOutboxUnpublishedEvents = `-- name: GetOutboxUnpublishedEvents :many
SELECT event_id, event_type, payload, created_at
FROM ocr.outbox
WHERE published_at IS NULL
ORDER BY created_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type GetOutboxUnpublishedEventsRow struct {
	EventID   pgtype.UUID        `json:"event_id"`
	EventType string             `json:"event_type"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetOutboxUnpublishedEvents(ctx context.Context, limit int32) ([]GetOutboxUnpublishedEventsRow, error) {
	rows, err := q.db.Query(ctx, getOutboxUnpublishedEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOutboxUnpublishedEventsRow
	for rows.Next() {
		var i GetOutboxUnpublishedEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventAsPublished = `-- name: MarkEventAsPublished :exec
UPDATE ocr.outbox
SET published_at = NOW()
WHERE event_id = $1
`

func (q *Queries) MarkEventAsPublished(ctx context.Context, eventID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEventAsPublished, eventID)
	return err
}
