// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package ocrdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateFilePage(ctx context.Context, arg CreateFilePageParams) error
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error
	DeleteFilePagesByFileID(ctx context.Context, fileID pgtype.UUID) error
	GetFilePagesByFileID(ctx context.Context, arg GetFilePagesByFileIDParams) ([]GetFilePagesByFileIDRow, error)
	GetOutboxUnpublishedEvents(ctx context.Context, limit int32) ([]GetOutboxUnpublishedEventsRow, error)
	MarkEventAsPublished(ctx context.Context, eventID pgtype.UUID) error
	UpdateFilePageText(ctx context.Context, arg UpdateFilePageTextParams) (OcrFilePage, error)
}

var _ Querier = (*Queries)(nil)
