// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package storagedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFile = `-- name: CreateFile :one
INSERT INTO storage.files (id, file_name, file_size, file_type, bucket_name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, file_name, file_size, file_type, bucket_name, created_at, updated_at
`

type CreateFileParams struct {
	ID         string `json:"id"`
	FileName   string `json:"file_name"`
	FileSize   int64  `json:"file_size"`
	FileType   string `json:"file_type"`
	BucketName string `json:"bucket_name"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (StorageFile, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.ID,
		arg.FileName,
		arg.FileSize,
		arg.FileType,
		arg.BucketName,
	)
	var i StorageFile
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FileSize,
		&i.FileType,
		&i.BucketName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFilesByIDs = `-- name: DeleteFilesByIDs :exec
DELETE FROM storage.files
WHERE id = ANY($1::text[])
`

func (q *Queries) DeleteFilesByIDs(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteFilesByIDs, dollar_1)
	return err
}

const getFiles = `-- name: GetFiles :many
SELECT 
    id, file_name, file_size, file_type, bucket_name, created_at, updated_at,
    COUNT(*) OVER() AS total
FROM storage.files
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetFilesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetFilesRow struct {
	ID         string             `json:"id"`
	FileName   string             `json:"file_name"`
	FileSize   int64              `json:"file_size"`
	FileType   string             `json:"file_type"`
	BucketName string             `json:"bucket_name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Total      int64              `json:"total"`
}

func (q *Queries) GetFiles(ctx context.Context, arg GetFilesParams) ([]GetFilesRow, error) {
	rows, err := q.db.Query(ctx, getFiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilesRow
	for rows.Next() {
		var i GetFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FileSize,
			&i.FileType,
			&i.BucketName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
