// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package storagedb

import (
	"context"
)

const countFiles = `-- name: CountFiles :one
SELECT COUNT(*) FROM storage.files
`

func (q *Queries) CountFiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO storage.files (id, file_name, file_size, file_type, bucket_name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, file_name, file_size, file_type, bucket_name, created_at, updated_at
`

type CreateFileParams struct {
	ID         string `json:"id"`
	FileName   string `json:"file_name"`
	FileSize   int64  `json:"file_size"`
	FileType   string `json:"file_type"`
	BucketName string `json:"bucket_name"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (StorageFile, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.ID,
		arg.FileName,
		arg.FileSize,
		arg.FileType,
		arg.BucketName,
	)
	var i StorageFile
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FileSize,
		&i.FileType,
		&i.BucketName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM storage.files
WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, file_name, file_size, file_type, bucket_name, created_at, updated_at FROM storage.files
WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id string) (StorageFile, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i StorageFile
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FileSize,
		&i.FileType,
		&i.BucketName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFiles = `-- name: GetFiles :many
SELECT id, file_name, file_size, file_type, bucket_name, created_at, updated_at FROM storage.files
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetFilesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetFiles(ctx context.Context, arg GetFilesParams) ([]StorageFile, error) {
	rows, err := q.db.Query(ctx, getFiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StorageFile
	for rows.Next() {
		var i StorageFile
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FileSize,
			&i.FileType,
			&i.BucketName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
