// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storagedb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type StorageFile struct {
	ID         string             `json:"id"`
	FileName   string             `json:"file_name"`
	FileSize   int64              `json:"file_size"`
	FileType   string             `json:"file_type"`
	BucketName string             `json:"bucket_name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
