// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storagedb

import (
	"context"
)

type Querier interface {
	CountFiles(ctx context.Context) (int64, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (StorageFile, error)
	DeleteFile(ctx context.Context, id string) error
	DeleteFilesByIDs(ctx context.Context, dollar_1 []string) error
	GetFileByID(ctx context.Context, id string) (StorageFile, error)
	GetFiles(ctx context.Context, arg GetFilesParams) ([]GetFilesRow, error)
}

var _ Querier = (*Queries)(nil)
