// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { filesServiceDeleteFiles, filesServiceGetFiles, healthServiceHealth, type Options, storageServiceConfirmFileUpload, storageServiceGetFileUrl, storageServiceGetUploadUrl } from '../sdk.gen';
import type { FilesServiceDeleteFilesData, FilesServiceDeleteFilesError, FilesServiceDeleteFilesResponse, FilesServiceGetFilesData, FilesServiceGetFilesError, FilesServiceGetFilesResponse, HealthServiceHealthData, HealthServiceHealthError, HealthServiceHealthResponse, StorageServiceConfirmFileUploadData, StorageServiceConfirmFileUploadError, StorageServiceConfirmFileUploadResponse, StorageServiceGetFileUrlData, StorageServiceGetFileUrlError, StorageServiceGetFileUrlResponse, StorageServiceGetUploadUrlData, StorageServiceGetUploadUrlError, StorageServiceGetUploadUrlResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const healthServiceHealthQueryKey = (options?: Options<HealthServiceHealthData>) => createQueryKey('healthServiceHealth', options);

/**
 * Health check
 *
 * Returns the health status of the service.
 */
export const healthServiceHealthOptions = (options?: Options<HealthServiceHealthData>) => queryOptions<HealthServiceHealthResponse, HealthServiceHealthError, HealthServiceHealthResponse, ReturnType<typeof healthServiceHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthServiceHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthServiceHealthQueryKey(options)
});

/**
 * Confirm File Upload
 *
 * Confirms that a file has been uploaded.
 */
export const storageServiceConfirmFileUploadMutation = (options?: Partial<Options<StorageServiceConfirmFileUploadData>>): UseMutationOptions<StorageServiceConfirmFileUploadResponse, StorageServiceConfirmFileUploadError, Options<StorageServiceConfirmFileUploadData>> => {
    const mutationOptions: UseMutationOptions<StorageServiceConfirmFileUploadResponse, StorageServiceConfirmFileUploadError, Options<StorageServiceConfirmFileUploadData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await storageServiceConfirmFileUpload({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const storageServiceGetFileUrlQueryKey = (options: Options<StorageServiceGetFileUrlData>) => createQueryKey('storageServiceGetFileUrl', options);

/**
 * Get File URL
 *
 * Retrieves a pre-signed URL for downloading a file.
 */
export const storageServiceGetFileUrlOptions = (options: Options<StorageServiceGetFileUrlData>) => queryOptions<StorageServiceGetFileUrlResponse, StorageServiceGetFileUrlError, StorageServiceGetFileUrlResponse, ReturnType<typeof storageServiceGetFileUrlQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await storageServiceGetFileUrl({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: storageServiceGetFileUrlQueryKey(options)
});

/**
 * Delete Files
 *
 * Deletes multiple files by their keys.
 */
export const filesServiceDeleteFilesMutation = (options?: Partial<Options<FilesServiceDeleteFilesData>>): UseMutationOptions<FilesServiceDeleteFilesResponse, FilesServiceDeleteFilesError, Options<FilesServiceDeleteFilesData>> => {
    const mutationOptions: UseMutationOptions<FilesServiceDeleteFilesResponse, FilesServiceDeleteFilesError, Options<FilesServiceDeleteFilesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await filesServiceDeleteFiles({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const filesServiceGetFilesQueryKey = (options?: Options<FilesServiceGetFilesData>) => createQueryKey('filesServiceGetFiles', options);

/**
 * Get Files
 *
 * Retrieves a paginated list of files.
 */
export const filesServiceGetFilesOptions = (options?: Options<FilesServiceGetFilesData>) => queryOptions<FilesServiceGetFilesResponse, FilesServiceGetFilesError, FilesServiceGetFilesResponse, ReturnType<typeof filesServiceGetFilesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await filesServiceGetFiles({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: filesServiceGetFilesQueryKey(options)
});

export const storageServiceGetUploadUrlQueryKey = (options?: Options<StorageServiceGetUploadUrlData>) => createQueryKey('storageServiceGetUploadUrl', options);

/**
 * Get Upload URL
 *
 * Generates a pre-signed URL for uploading files.
 */
export const storageServiceGetUploadUrlOptions = (options?: Options<StorageServiceGetUploadUrlData>) => queryOptions<StorageServiceGetUploadUrlResponse, StorageServiceGetUploadUrlError, StorageServiceGetUploadUrlResponse, ReturnType<typeof storageServiceGetUploadUrlQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await storageServiceGetUploadUrl({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: storageServiceGetUploadUrlQueryKey(options)
});
